vim.keymap.set("n", "<leader>pv", "<cmd>Ex<CR>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("v", "c", "\"_c")
vim.keymap.set("n", "c", "\"_c")
vim.keymap.set("n", "Y", "yg$")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "Q", "<nop>")
-- Traverse Quickfix list and Location list
vim.keymap.set("n", "<C-j>", "<cmd>cnext<CR>zz")
vim.keymap.set("n", "<C-k>", "<cmd>cprev<CR>zz")
vim.keymap.set("n", "<leader>j", "<cmd>lnext<CR>zz")
vim.keymap.set("n", "<leader>k", "<cmd>lprev<CR>zz")
-- Resize window
vim.keymap.set("n", "<A-j>", "<cmd>winc -<CR>")
vim.keymap.set("n", "<A-k>", "<cmd>winc +<CR>")
vim.keymap.set("n", "<A-h>", "<cmd>5winc <<CR>")
vim.keymap.set("n", "<A-l>", "<cmd>5winc ><CR>")
